<?php

class TextformatterImageTags extends Textformatter {

	public static function getModuleInfo() {
		return array(
			'title' => 'Image Tags', 
			'version' => 101, 
			'summary' => "Allows you to insert images in a text area by referencing them with tags in the format {fieldName:n}",
			'href' => 'http://processwire.com/talk/topic/1182-module-image-tags/',
		); 
	}

	public function format(&$str) {
		if(strpos($str, '{') === false) return; // check if we even need to perform a preg_match and exit if not (added by Ryan)
		preg_match_all("/{[\w]*:[\d]*}/", $str, $array);
		foreach($array[0] as $match){
	   		$nobrackets = str_replace(array("{","}"),"",$match);
	   		$exploded = explode(":",$nobrackets);
	   		$field = $this->page->$exploded[0];
	        $number = $exploded[1];
	        $index = $number-1;
	        if($field instanceof Pageimages){
	        	if($number){
	        		$image = $field->eq($index);
	        		$thumb = $image->width(2880, array('upscaling'=>false, 'cropping'=>false));
	        		$image = "<div class='image'><img class='ImageTags' src='$thumb->url' alt='$image->description'><div class='caption'>$image->description</div></div>";
	        	} else {
	        		$image = "";
	        		foreach($field as $img)
	     				$image .= "<div class='image'><img class='ImageTags' src='$img->url' alt='$img->description'><div class='caption'>$image->description</div></div>";
	     		}
	        } else if($field instanceof Pageimage){
	        	$image = "<div class='image'><img class='ImageTags' src='$field->url' alt='$field->description'><div class='caption'>$image->description</div></div>";
	     	} else {
	     		$image = "";
	     	}
	        $str = str_replace($match, $image, $str);
	   }
	}
}